### PR TITLE
Hey Can you add some support for 2Captcha

### PR DESCRIPTION
**Pull request by WaltDisneyWorld**
Mind Adding 2Captcha support, and maybe a way to control these bots eg: following users using the tokens generated?

### CODE REVIEW

**Comment by Morb0** [comment]
Unfortunately, I'm not interested in supporting this project, I only needed it to get the keys for the Valorant Beta.

**Comment by WaltDisneyWorld** [comment]
Oh, but you dont' need to change much to make it work with 2Captcha.
________________________________

**Comment by Morb0** [comment]
As far as I remember, there is already rucapcha support. And rucapcha is the same as 2capcha.

**Comment by WaltDisneyWorld** [comment]
Not exactly, I can share the code via discord. Add me: `Caleb.#0756`

("Caleb.#0756")

**Comment by WaltDisneyWorld** [comment]
^

**Comment by Morb0** [comment]
Better write here if you want something.

**Comment by ghost** [comment]
can you help me?  (i ve tried run this on ubuntu and termux but not works) i need install a requisite? or something, i already have node
LOGS:
~/valorant-drops-helper $ node twitch.js
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'axios'
Require stack:
- /data/data/com.termux/files/home/valorant-drops-helper/twitch.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/data/data/com.termux/files/home/valorant-drops-helper/twitch.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/data/data/com.termux/files/home/valorant-drops-helper/twitch.js'
  ]
}

**Comment by Morb0** [comment]
Yes, you need to install dependencies using `npm install` in root with `package.json`.

**Comment by WaltDisneyWorld** [comment]
Pleas ehelp me fix this:
```const axios = require('axios');
// https://www.twitch.tv/signup


module.exports.solveFunCaptcha = async (publicKey, sURL, pageURL) => {
  const surl = "https://client-api.arkoselabs.com"
  
    const {data} = await axios.get('https://2captcha.com/in.php', {
        params: {
            key: process.env.RUCAPTCHA_KEY,
            method: 'funcaptcha',
            publickey: publicKey,
            surl: process.env.sURL,
           pageurl: process.env.pageURL,
            json: 1,
        },
    });
console.log (surl,publicKey, pageURL,pageurl)
    if (data.status === 0)
        throw new Error(`Failed to solve captcha: ${data.error_text}`);

    const taskId = data.request;
    const captchaToken = await getCaptchaResult(taskId);
    return captchaToken;
};
const pageurl = "https://www.twitch.tv/signup?no-mobile-redirect=true"
const getCaptchaResult = taskId => {
    return new Promise(async (resolve, reject) => {
        const checkResult = async () => {
            const {data} = await axios.get('https://2captcha.com/res.php', {
                params: {
                    key: process.env.RUCAPTCHA_KEY,
                    action: 'get',
                    id: taskId,
                    surl: sURL,
                    pageurl: pageURL,
                    json: 1,
                },
            });

            if (data.status === 0) {
                if (data.request === 'CAPCHA_NOT_READY') {
                    setTimeout(() => checkResult(), 5000);
                    return;
                }

                return reject(`Failed to get captcha result: ${data.error_text || data.request}`);
            }

            resolve(data.request);
        };
        await checkResult();
    });
};
```

**Pull request closed without merging**
